# code: language=ansible
---
- name: Create/update systemd unit file
  ansible.builtin.template:
    src: minikube.service.j2
    dest: /lib/systemd/system/minikube.service
    mode: "0644"
  notify: restart minikube
- name: Service minikube is active and enabled on system startup
  ansible.builtin.systemd_service:
    name: minikube
    state: started
    enabled: true
# - name: allow minikube port
#   community.general.ufw:
#     rule: allow
#     port: "123456"
